Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.provision "shell", path: "docker_install.sh"
  config.vm.provider "virtualbox" do |v|
    v.name = "docker-produtivo"
    v.memory = 2536
    v.cpus = 2
  end
  config.vm.provider "parallels" do |v, override|
    override.vm.box = "parallels/ubuntu-14.04"
    v.name = "docker-produtivo"
    v.optimize_power_consumption = false
    v.memory = 2536
    v.cpus = 2
  end
end
