Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = "docker/mysql"
    d.ports = ["3306:3306"]
    d.vagrant_vagrantfile = "./docker/host/Vagrantfile"
  end

end
